---

- name: Copy helm install shell script
  copy:
    src: install_tiller.sh
    dest: "/home/{{ ssh_user }}/install_tiller.sh"
    owner: hawk
    group: hawk
    mode: '0744'
  register: helm_script


  #- name: Execute helm install script
  #  shell: "/home/{{ ssh_user }}/install_tiller.sh"
  #  when: helm_script is changed
