---

- hosts: ranchers
  roles:
    - docker
      #    - rancher_dl
      #    - rancher-cluster
      #  tasks:
      #  - name: "Insert passwordless sudo for ssh_user"
      #    lineinfile:
      #      path: /etc/sudoers
      #      line: "{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL"
      #    become: true
      #
      #- hosts: rancher_master
      #  roles:
      #    - helm
      #
      #- hosts: loadbalancer
      #  roles:
      #    - haproxy
      #  tasks:
      #  - name: "Insert passwordless sudo for ssh_user"
      #    lineinfile:
      #      path: /etc/sudoers
      #      line: "{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL"
      #    become: true
- hosts: rancher1
  roles:
    - role: pgsql
      tags: pgsql

- hosts: ranchers
  serial: 1
  roles:
    - role: k3s-rancher-server
      tags: k3s-rancher
