---

- name: Install prerequisites
  apt:
    name: ['ca-certificates']
    update_cache: yes
  become: yes

- name: Add postgress apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Add postgres APT repository
  apt_repository:
    repo: deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main
  become: yes

- name: "Install pgsql {{pgsql_version}}"
  apt:
    pkg:
    -  "postgresql={{pgsql_version}}"
    -  "python3-psycopg2"
  become: yes

- name: Enable pinned pgsql version
  template:
    src: "pgsql.pref.j2"
    dest: "/etc/apt/preferences.d/pgsql.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes

- name: Enable tcp for CIDR
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    line: 'host    all             all             192.168.5.1/23            md5'
  become: yes
  register: hba_conf

- name: Enable tcp for CIDR
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    line: "listen_addresses = '*'"
  become: yes
  register: pg_listen

- name: restart postgres
  systemd:
    state: restarted
    name: postgresql
  when: hba_conf is changed or pg_listen is changed
  become: yes


- name: Create a new database with name "rancher"
  postgresql_db:
    name: rancher
    state: present
  become: yes
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true

- name: Connect to rancher database, create rancher user
  postgresql_user:
    db: rancher
    name: "{{ rancher_db_user }}"
    password: "{{ rancher_db_passwd }}"
    priv: "ALL"
  become: yes
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
