---

- name: "Download rke"
  get_url:
    url: "https://github.com/rancher/rke/releases/download/v{{ rancher_version }}/rke_linux-amd64"
    dest: "/usr/local/bin/rke"
    checksum: "sha256:{{ rancher_checksum }}"
    mode: '0655'
  become: true

- name: "Download kubectl"
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: '0655'
  become: true

- name: "Download helm"
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    checksum: "sha256:{{ helm_checksum }}"
    dest: "/root/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    mode: '0655'
  become: true
  register: dl_helm

- name: Extract Helm
  unarchive:
    src: "/root/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true
  become: true
  when: dl_helm is changed

- name: Copy Helm
  copy: remote_src=True src=/tmp/linux-amd64/helm dest=/usr/local/bin/helm mode=0755
  become: true
  when: dl_helm is changed

- name: Remove old files helm
  file: path=/tmp/linux-amd64 state=absent
  become: true
  when: dl_helm is changed
