---

- name: Install cluster.yml
  template:
    src: cluster.yml.tmpl
    dest: "/home/{{ ssh_user }}/cluster.yml"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0644'

- name: "Insert KUBECONFIG  for user {{ ssh_user }}"
  lineinfile:
    path: "/home/{{ ssh_user }}/.bashrc"
    line: "export KUBECONFIG=/home/{{ ssh_user }}/kube_config_cluster.yml"
  become: true

- debug:
    msg: "Runs rke upp in {{ ssh_user }} home folder"
