---

- name: Install prerequisites
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
    update_cache: yes
  become: yes

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes


- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
  become: yes


- name: "Install docker-ce {{docker_version}}"
  apt:
    pkg:
    -  "docker-ce={{docker_version}}"
    -  "docker-ce-cli={{docker_version}}"
    -  "containerd.io"
  become: yes


- name: Enable pinned Docker version
  template:
    src: "docker.pref.j2"
    dest: "/etc/apt/preferences.d/docker.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes

- name: Enable pinned Docker cli version
  template:
    src: "docker-cli.pref.j2"
    dest: "/etc/apt/preferences.d/docker-cli.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes

- name: adding existing user '{{ ssh_user }}' to group docker
  user:
    name: "{{ ssh_user }}"
    groups: docker
    append: yes
  become: yes
